
$(document).ready(function(){
    $(".navbar-toggler").click(function(){
       $(".navbar-collapse").toggleClass("h-32");
    });
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:30,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            1200:{
                items:3
            }
        }
    });
});